### ISSUE TITLE
Prompt for oxd settings and install it if needed

### ISSUE THREAD

**Issue by yurem** [GluuFederation/post-installation-setup#2]
According to @jgomer2001 :

1. Ask user "Do you have an existing oxd-server installation? Note: oxd is used to integrate this product with the Gluu Server OP."
1.1 if not, go to step 2
1.2 if yes prompt: Enter oxd-server hostname [localhost]
1.2.1 if localhost was entered, go to step 3
1.2.2 if it's a host other than localhost, display "To use a host other than localhost, the oxd-https-extension is required on that server, proceed?"
1.2.2.1 if yes, go to step 3
1.2.2.2 if not, go to step 1.2

2. display "Install oxd-server on this host now?" 
Proceed?"
2.1 if not, display "An oxd server instance is required when installing this product via Linux packages", and abort installation
2.2 if yes
2.2.1 Prompt "Do you have a license of oxd? (If not, get your license by registering on: https://oxd.gluu.org)" [Y/n]
2.2.1.1 if not, display: "Get your license on https://oxd.gluu.org to proceed with installation."
2.2.1.2 if yes, download the zip of oxd (this way we don't have to worry about underlying OS), and unzip the contents to a folder.
2.2.1.2.1 Ask user to enter the license data.
2.2.1.2.2 Modify the oxd-config.json file with these values
2.2.1.2.3 Change permissions so oxd-start.sh is executable
2.2.1.2.4 Launch oxd in the background (display a message for this)
2.2.1.2.5 go to step 4

3. prompt: Enter oxd server port: [8098] (here if we know the https extension is used, the default port should be 8443 - to keep it aligned with the current oxd docs and avoid confusion) 

4. Fill the properties related to oxd in cred-manager.json including "use_https_extension" (current setup_cred_manager.py is not setting it)

**Comment by willow9886** [comment]
> 1.2 if yes prompt: Enter oxd-server hostname [localhost]
> 1.2.1 if localhost was entered, go to step 3
> 1.2.2 if it's a host other than localhost, display "To use a host other than localhost, the oxd-https-extension is required on that server, proceed?"


I think this should be more like:

Will this product use localhost sockets [1] or https [2] to connect to oxd-server? [1|2] 

If 1, then:

Enter the port of your oxd-server:

If 2, then: 

Enter the URL of your oxd-server:

**Comment by willow9886** [comment]
#1 
Ask user:  "Do you have an existing oxd-server installation? Note: oxd is commercial software used to integrate this product with the Gluu Server OpenID Provider (OP)." [Y | N]

1.1 if N, go to step 2.

1.2 if Y prompt: "Will this product use localhost [1] or https [2] to connect to oxd-server? [1|2]"

1.2.1 if localhost [1] was entered, prompt: "Enter the port of your oxd-server (e.g. 8098):   "

1.2.2 if https [2] was entered, prompt: "Enter the URL + port of your oxd-server (e.g. https://oxd.example.com:8443):    "

1.2.3 Go to step 3

# 2 
Display "Install oxd-server on this host now?" [Y | N]

2.1 if N, display "oxd-server is required to install this product via Linux packages." and abort installation.

2.2 if Y, download the zip of oxd and unzip the contents to a folder.

2.2.1 Prompt: “Enter your license information (obtain a license on https://oxd.gluu.org or press enter to skip this step and manually add your license later):  “ 

2.2.2 If no license entered, go to step 3. Otherwise move on to steps 2.3 - 2.3.3

2.3 Modify the oxd-config.json file with these values

2.3.1 Change permissions so oxd-start.sh is executable

2.3.2 Launch oxd in the background (display a message for this)

2.3.3 Go to step 3

# 3 (not user facing)
Fill the properties related to oxd in cred-manager.json:

Setup_cred_manager.py (see render_templates  routine) is generating a json file based from this sample https://github.com/GluuFederation/cred-manager/blob/master/configurations/cred-manager.json. Currently it is missing to set the proper values for the oxd settings being gathered (see #L3-#L7).

"use_https_extension" is a boolean that should be set to true/false whether https extension is being used or not (determined during step 1). 


![image](https://user-images.githubusercontent.com/5271048/34531891-93d0611e-f079-11e7-9e44-a59b5a64b1a4.png)

**Comment by jgomer2001** [comment]
@arvindsinghtomar, I have 2 comments so far

- oxd should be installed even if the user did not provide license info at installation prompts. He can go for those details afterwards and do config file adjustments manually. And when no license is provided, we should simply not run `oxd-start.sh`. 
(maybe there was some misunderstanding or ambiguity around step 2.2.2, but it's ok since in practice we first do all prompts, and then installation, while algorithm was assuming that in step 2.2 oxd was being installed).

- there is no need to prompt for OP host, I think we can remove this. We can leave "op_host" empty in `oxd-default-site-config.json` and for "server_name" in `oxd-conf.json` we can set the host name based on issuer (property in ldap) or somewhere else. The less prompts the better.

![ophost](https://user-images.githubusercontent.com/5444180/35159772-513f992c-fd09-11e7-8007-98bd911737d5.png)

**Comment by yurem** [comment]
Instead of 'oxd-start.sh' se should start 'service oxd-service start'

**Comment by jgomer2001** [comment]
> should run 'service oxd-service start'

True!

@arvindsinghtomar 
Additionally, property `use_https_extension` is boolean-ish, but it's being set as string currently.
This is the right way to set it:
* `true` if the algorithm took algorithm branch 1.2.2
* `false` otherwise. That is, user provided a standard localhost oxd-server or the oxd-server installation was performed by this script

**Comment by jgomer2001** [comment]
>Additionally, property use_https_extension is boolean-ish, but it's being set as string currently...

Apparently, there was no work in this regard. For example, this is what I see when oxd installation was performed by the script and license info was provided. In this case, it  should be `use_https_extension: false` ...
![cred_mgr_json_license](https://user-images.githubusercontent.com/5444180/35286623-857ccd9a-002e-11e8-9705-9b421a4633bf.png)

Let's take the chance to apply the following fix: Change all occurrences of 8098 by 8099. The last one is the default port of oxd - the algorithm has a typo.

**Comment by jgomer2001** [comment]
Changed to use 8099, https://github.com/GluuFederation/post-installation-setup/commit/e2dd73138ff1a224e030b61ebed5b97e7eb367d1
